# Generated by Django 5.0.6 on 2024-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_in_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stocks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
