# Generated by Django 5.0.6 on 2024-07-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
