# Generated by Django 5.0.6 on 2024-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('DUE', 'DUE'), ('ACCEPTED', 'ACCEPTED'), ('VALID', 'VALID'), ('NEW', 'NEW')], default='NEW', max_length=50),
        ),
    ]
