# Generated by Django 5.0.6 on 2024-07-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED'), ('DUE', 'DUE'), ('CANCELLED', 'CANCELLED'), ('VALID', 'VALID'), ('NEW', 'NEW')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.CharField(max_length=300),
        ),
    ]
