# Generated by Django 5.0.6 on 2024-07-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DUE', 'DUE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('VALID', 'VALID'), ('NEW', 'NEW')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
