# Generated by Django 5.0.6 on 2024-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DUE', 'DUE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('NEW', 'NEW'), ('VALID', 'VALID')], default='NEW', max_length=50),
        ),
    ]
