# Generated by Django 5.0.6 on 2024-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('NEW', 'NEW'), ('CANCELLED', 'CANCELLED'), ('DUE', 'DUE'), ('ACCEPTED', 'ACCEPTED'), ('VALID', 'VALID')], default='NEW', max_length=50),
        ),
    ]
