# Generated by Django 5.0.6 on 2024-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED'), ('NEW', 'NEW'), ('CANCELLED', 'CANCELLED'), ('VALID', 'VALID'), ('DUE', 'DUE')], default='NEW', max_length=50),
        ),
    ]
