# Generated by Django 5.0.6 on 2024-07-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('VALID', 'VALID'), ('COMPLETED', 'COMPLETED'), ('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW'), ('DUE', 'DUE')], default='NEW', max_length=50),
        ),
    ]
